# Generated by Django 3.1.7 on 2021-03-26 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('numero', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_exp', models.DateField()),
            ],
            options={
                'verbose_name': 'CPF',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cpf')),
                ('departamentos', models.ManyToManyField(blank=True, null=True, to='core.Departamento')),
            ],
            options={
                'verbose_name': 'Cadastro de Empregado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=80)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empregado')),
            ],
            options={
                'verbose_name': 'Cadastro de Telefone',
            },
        ),
    ]
