# Generated by Django 3.1.7 on 2021-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=10000)),
                ('previsao_2019', models.BooleanField()),
                ('previsao_2017', models.BooleanField()),
                ('previsao_2015', models.BooleanField()),
                ('previsao_2010', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('abertura', models.FloatField()),
                ('close', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('variacao', models.CharField(blank=True, max_length=20, null=True)),
                ('previsao_normal', models.CharField(blank=True, max_length=20, null=True)),
                ('mm9', models.FloatField()),
                ('mm21', models.FloatField()),
                ('bb_sup', models.FloatField()),
                ('bb_inf', models.FloatField()),
                ('previsao_return', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao_pont', models.CharField(max_length=20)),
                ('nota', models.FloatField()),
                ('oscilacao', models.FloatField()),
                ('data_base', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaleComigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('colaboracao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('media_naive', models.FloatField()),
                ('desvio_naive', models.FloatField()),
                ('class_naive', models.CharField(blank=True, max_length=50, null=True)),
                ('predict_class_naive', models.CharField(blank=True, max_length=50, null=True)),
                ('media_arvores', models.FloatField()),
                ('desvio_arvores', models.FloatField()),
                ('class_arvores', models.CharField(blank=True, max_length=50, null=True)),
                ('predict_class_arvores', models.CharField(blank=True, max_length=50, null=True)),
                ('media_random', models.FloatField()),
                ('desvio_random', models.FloatField()),
                ('class_random', models.CharField(blank=True, max_length=50, null=True)),
                ('predict_class_random', models.CharField(blank=True, max_length=50, null=True)),
                ('media_knn', models.FloatField()),
                ('desvio_knn', models.FloatField()),
                ('class_knn', models.CharField(blank=True, max_length=50, null=True)),
                ('predict_class_knn', models.CharField(blank=True, max_length=50, null=True)),
                ('media_svc', models.FloatField()),
                ('desvio_svc', models.FloatField()),
                ('class_svc', models.CharField(blank=True, max_length=50, null=True)),
                ('predict_class_svc', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered_ranking', models.CharField(max_length=500)),
                ('ordered_ranking2', models.CharField(max_length=500)),
                ('data_base', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Simulador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('valor', models.FloatField()),
            ],
        ),
    ]
